print "AND neg: " + str(-5 & -3)
print "OR neg: " + str(-1 | 5)
print "XOR neg: " + str(-10 ^ 15)
print "NOT zero: " + str(~0)
print "NOT -1: " + str(~-1)
print "AND mask: " + str(255 & 15)
print "OR mask: " + str(240 | 15)
print "XOR same: " + str(255 ^ 255)
print "Float AND: " + str(5.5 & 3.2)
print "Float OR: " + str(10.9 | 2.1)
print "Nil AND left: " + str(nil & 5)
print "Nil OR right: " + str(10 | nil)
print "Nil NOT: " + str(~nil)
print "Chained bitwise: " + str((10 & 7) | (15 ^ 3))
