# Test startswith and endswith string builtins edge cases
print "1. " + str(startswith("hello world", "hello"))
print "2. " + str(endswith("hello world", "world"))
print "3. " + str(startswith("hello world", "world"))
print "4. " + str(endswith("hello world", "hello"))
print "5. " + str(startswith("hello", ""))
print "6. " + str(endswith("hello", ""))
print "7. " + str(startswith("hello", "hello"))
print "8. " + str(endswith("hello", "hello"))
print "9. " + str(startswith("hi", "hello"))
print "10. " + str(endswith("hi", "hello"))
print "11. " + str(startswith("", "a"))
print "12. " + str(endswith("", "a"))
print "13. " + str(startswith("", ""))
print "14. " + str(endswith("", ""))
print "15. " + str(startswith("Hello", "hello"))
print "16. " + str(endswith("World", "world"))
print "17. " + str(startswith(nil, "a"))
print "18. " + str(startswith("hello", nil))
