var a = [10, 20, 30]
print("len=" + str(len(a)))
print("a[0]=" + str(a[0]))
a[1] = 50
print("a[1]=" + str(a[1]))
var b = a[0:2]
var slen = len(b)
print("slice_len=" + str(slen))
print("b[0]=" + str(b[0]))
print("b[1]=" + str(b[1]))
